apiVersion: v1
kind: ConfigMap
metadata:
  name: elvakt-backend-config
  namespace: elvakt
data:
  PROJECT_NAME: ElVakt
  VERSION: "1.0.0"
  ENVIRONMENT: production
  DEBUG: "false"
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:30000","http://127.0.0.1:3000"]'
  BASE_API_URL: https://www.elprisetjustnu.se/api/v1/prices
