apiVersion: v1
kind: Secret
metadata:
  name: elvakt-backend-secret
  namespace: elvakt
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://change_me:change_me@elvakt-postgres:5432/change_me
