apiVersion: v1
kind: Secret
metadata:
  name: elvakt-postgres-secret
  namespace: elvakt
type: Opaque
stringData:
  POSTGRES_DB: change_me
  POSTGRES_USER: change_me
  POSTGRES_PASSWORD: change_me
